"""make contact leadid unique

Revision ID: 3f1775edf860
Revises: a3c40442e7cd
Create Date: 2026-09-22 20:05:46.219851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1775edf860'
down_revision: Union[str, None] = 'a3c40442e7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Contact_leadId_idx', table_name='Contact')
    op.create_index('Contact_leadId_key', 'Contact', ['leadId'], unique=True, postgresql_where=sa.text('"leadId" IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Contact_leadId_key', table_name='Contact', postgresql_where=sa.text('"leadId" IS NOT NULL'))
    op.create_index('Contact_leadId_idx', 'Contact', ['leadId'], unique=False)
    # ### end Alembic commands ###
