"""add_lead_desired_treatment

Revision ID: 87837a6342ab
Revises: d512c571e9cb
Create Date: 2026-09-21 13:45:11.782606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87837a6342ab'
down_revision: Union[str, None] = 'd512c571e9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lead', sa.Column('desiredTreatment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Lead', 'desiredTreatment')
    # ### end Alembic commands ###
