"""Add Contact table

Revision ID: a3c40442e7cd
Revises: dd0136dd6857
Create Date: 2026-09-22 19:16:56.505854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3c40442e7cd'
down_revision: Union[str, None] = 'dd0136dd6857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patientId', sa.UUID(), nullable=True),
    sa.Column('leadId', sa.UUID(), nullable=True),
    sa.Column('appointmentId', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CONTACTED', 'COMPLETED', 'NO_RESPONSE', 'CANCELLED', name='ContactStatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('nextFollowUpAt', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=False),
    sa.Column('deletedAt', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.ForeignKeyConstraint(['appointmentId'], ['Appointment.id'], name='Contact_appointmentId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leadId'], ['Lead.id'], name='Contact_leadId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patientId'], ['Patient.id'], name='Contact_patientId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Contact_leadId_idx', 'Contact', ['leadId'], unique=False)
    op.create_index('Contact_patientId_idx', 'Contact', ['patientId'], unique=False)
    op.create_index('Contact_status_idx', 'Contact', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Contact_status_idx', table_name='Contact')
    op.drop_index('Contact_patientId_idx', table_name='Contact')
    op.drop_index('Contact_leadId_idx', table_name='Contact')
    op.drop_table('Contact')
    # ### end Alembic commands ###
