"""create_lead_domain

Revision ID: d512c571e9cb
Revises: d6200097af4c
Create Date: 2026-09-21 10:18:36.033425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd512c571e9cb'
down_revision: Union[str, None] = 'd6200097af4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lead',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CONVERTED', 'DISMISSED', name='LeadStatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=False),
    sa.Column('deletedAt', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Lead_phone_idx', 'Lead', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Lead_phone_idx', table_name='Lead')
    op.drop_table('Lead')
    # ### end Alembic commands ###
