"""add_refresh_token_rotation_and_lineage

Revision ID: d6200097af4c
Revises: 3f41612e6086
Create Date: 2026-09-21 10:16:31.599561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6200097af4c'
down_revision: Union[str, None] = '3f41612e6086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RefreshToken', sa.Column('familyId', sa.UUID(), nullable=False))
    op.add_column('RefreshToken', sa.Column('replacedBy', sa.UUID(), nullable=True))
    op.add_column('RefreshToken', sa.Column('revokedAt', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True))
    op.create_index('RefreshToken_familyId_idx', 'RefreshToken', ['familyId'], unique=False)
    op.create_index('RefreshToken_hashedToken_key', 'RefreshToken', ['hashedToken'], unique=True)
    op.create_foreign_key('RefreshToken_replacedBy_fkey', 'RefreshToken', 'RefreshToken', ['replacedBy'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('RefreshToken_replacedBy_fkey', 'RefreshToken', type_='foreignkey')
    op.drop_index('RefreshToken_hashedToken_key', table_name='RefreshToken')
    op.drop_index('RefreshToken_familyId_idx', table_name='RefreshToken')
    op.drop_column('RefreshToken', 'revokedAt')
    op.drop_column('RefreshToken', 'replacedBy')
    op.drop_column('RefreshToken', 'familyId')
    # ### end Alembic commands ###
