"""add_blog_metadata

Revision ID: dd0136dd6857
Revises: e1a7e654fb35
Create Date: 2026-09-21 21:57:38.039915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd0136dd6857'
down_revision: Union[str, None] = 'e1a7e654fb35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blog', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('Blog', sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Blog', 'tags')
    op.drop_column('Blog', 'category')
    # ### end Alembic commands ###
