"""create_blog_domain

Revision ID: e1a7e654fb35
Revises: 87837a6342ab
Create Date: 2026-09-21 20:58:34.473684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1a7e654fb35'
down_revision: Union[str, None] = '87837a6342ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('coverImage', sa.Text(), nullable=True),
    sa.Column('authorId', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='BlogStatus'), nullable=False),
    sa.Column('publishedAt', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=False),
    sa.Column('deletedAt', postgresql.TIMESTAMP(timezone=True, precision=3), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['User.id'], name='Blog_authorId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Blog_slug_key', 'Blog', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Blog_slug_key', table_name='Blog')
    op.drop_table('Blog')
    # ### end Alembic commands ###
