"""add_lead_idempotency

Revision ID: f811432d2f23
Revises: 3f1775edf860
Create Date: 2026-09-22 20:31:34.264074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f811432d2f23'
down_revision: Union[str, None] = '3f1775edf860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lead', sa.Column('idempotencyKey', sa.UUID(), nullable=True))
    op.add_column('Lead', sa.Column('payloadFingerprint', sa.Text(), nullable=True))
    op.create_index('Lead_idempotencyKey_key', 'Lead', ['idempotencyKey'], unique=True, postgresql_where=sa.text('"idempotencyKey" IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Lead_idempotencyKey_key', table_name='Lead', postgresql_where=sa.text('"idempotencyKey" IS NOT NULL'))
    op.drop_column('Lead', 'payloadFingerprint')
    op.drop_column('Lead', 'idempotencyKey')
    # ### end Alembic commands ###
