import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

// Runtime Signature Telemetry
(() => {
  const _0x4f1a = "CuKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKjgOKjgOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggArioIDioIDioIDioIDioIDioIDioIDioIDioIDioIDioIDioIDioIDioIDio6Dio7bioJvioJvioJvioJvioLfio7bio6Tio4DioIDioIDioIDioIDioIDioIAK4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qOw4qCf4qCB4qCI4qKz4qGAwq7iooDio6Dio7Tiob/ioL/ioJvioIDioIDioIDioIDioIAK4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qKA4qGe4qCB4qCA4qCA4qCA4qCA4qO/4qO/4qO/4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCACuKggOKggOKggOKggOKggOKggOKggOKggOKggOKigOKhvuKggOKigOKjoOKjpOKjhOKiuOKjv+Kjv+Kjv+KggOKggOKggOKggOKggOKggOKggOKggOKggOKggArioIDioIDioIDioIDioIDioIDioIDioIDioIDio77ioIHioIDio77ioIvioIjioLnio7/io7/io7/io7/ioYfioIDioIDioIDioIDioIDioIDioIDioIDioIAK4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qK44qGPIOKggOKiu+KhhuKggOKggOKiueKjv+Kjv+Kjv+Khh+KggOKggOKggOKggOKggOKggOKggOKggOKggArioIDioIDioIDioIDioIDioIDioIDioIDiorjioYcgRSDiorjioYfioIDioIDioIjio7/io7/io7/ioIDioIDioIDioIDioIDioIDioIDioIDioIDioIAK4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qK44qGHIFIg4qK44qOH4qCA4qCA4qCA4qO/4qO/4qG/4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCACuKggOKggOKggOKggOKggOKggOKggOKggOKiuOKhhyAwIOKiuOKjv+KggOKggOKioOKjv+Kjv+Khh+KggOKggOKggOKggOKggOKggOKggOKggOKggOKggArioIDioIDioIDioIDioIDioIDioIDioIDioLjio7fioIBS4qCI4qO/4qCA4qKA4qO+4qO/4qO/4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCACuKggOKggOKggOKggOKggOKggOKggOKggOKggOKjv+KhgOKggOKggOKgu+KituKjv+Kjv+Kjv+Khh+KggOKggOKggOKggOKggOKggOKggOKggOKggOKggArioIDioIDioIDioIDioIDioIDioIDiooDio6Tiob7ioIPioIDioIDioIDioIjio7/io7/io7/ioIHioIDioIDioIDioIDioIDioIDioIDioIDioIDioIAK4qCA4qCA4qCA4qCA4qCA4qKg4qO24qOv4qOk4qOk4qOk4qOk4qG04qC24qC24qO84qO/4qO/4qO34qOk4qOA4qCA4qCA4qCA4qCA4qCA4qCA4qCA4qCACuKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKggOKgieKgieKgieKggeKggOKggAogIAogICAgICAgUCBBIE4gRyBPIFMgTyBSIE8gUwogIA==";
  const _0x9b2c = decodeURIComponent(escape(atob(_0x4f1a)));
  const _0x1c8e = 'color: #55ff00; font-family: monospace; font-size: 13px; text-shadow: 0 0 8px rgba(85,255,0,0.6);';
  console.log(`%c${_0x9b2c}`, _0x1c8e);
})();

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
